typography_spectrum: 0.291036473819986
content_rating:
  adult: false
color:
  brandStrength: 0.9885722047183663
  lightness: 0.0060058580711483955
  saturation: 0.3925518705509603
  rhythmicContrast: 0.6350105162709951
  brandColors:
    - '#105B63'
    - '#FFFAD5'
    - '#FFD34E'
    - '#DB9E36'
    - '#BD4932'
layout_spectrum: 0.11965391994453967
author:
  name: Ryan Fickling
  email: na
  url: 'https://thegrid.ai/fickling-media-llc/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b745f06a-1449-442f-84c9-599cb715e4ee.jpg
name: Bee Me
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/468098f3-8989-42c5-9200-854058b1904c.jpg
title: Bee Everything
